title:            Premier Projet sur Jekyll
description:      Localisation du Thème So Simple
logo:             site-logo.png
disqus_shortname: xtof
search:           true
#Modifiez l'url vers votre domaine. Laissez le serveur en localhost ou en blanc pendant que vous travaillez localement.
url:              http://christopheducamp.github.io/so-simple-theme-fr

# Info Propriétaire/auteur
owner:
  name:           Christophe Ducamp
  avatar:         christophe-ducamp-photo.jpg
  email:          christophe@mydatalabs.com
  # Les liens vers les silos sociaux utilisés dans le footer. Mettez à jour et retirer à votre gré.
  twitter:  xtof_fr      
  facebook:  christophe.ducamp    
  github: christopheducamp         
  stackexchange:  
  linkedin: christopheducamp      
  instagram: xtof_fr     
  flickr: christopheducamp/    
  tumblr: xtof         
  # Pour la paternité d'auteur Google + https://plus.google.com/authorship
  google_plus: https://plus.google.com/+ChristopheDucamp
# Les analytics et outils de webmaster se placent ici 
google_analytics: UA-46686084-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Liens à inclure tout en haut
# Pour des liens externes ajoutez external: true
links:
  - title: À Propos
    url: /about
  - title: Articles
    url: /articles
  - title: Réglage Thème
    url: /theme-setup
  - title: Made Mistakes
    url: http://mademistakes.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
